apiVersion: apps/v1
kind: Deployment
metadata:
  name: secondo-nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secondo-nginx
  template:
    metadata:
      labels:
        app: secondo-nginx
    spec:
      containers:
      - name: nginx
        image: localhost/secondo-nginx:v20250405124208
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: secondo-nginx-service
spec:
  selector:
    app: secondo-nginx
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
